### PR TITLE
Use next page url from the middleware response to load additional data

### LINKED ISSUE #32: Sometimes a generation is skipped between "cached" and the dynamically fetched
image

This is kinda tricky to reproduce but happened to me few times
I think when you open the page in a specific interval between the latest cached generation (which apparently in the backend is 1 gen behind) and few second before the new generation is dynamically added it misses the one between. I guess it is backend related

It gets in sync after several minutes though

### PR DESCRIPTION
**Pull request by CedrikNikita**
fixes #32,
fixes problem with duplicate names
duplicate names

### CODE REVIEW

**Comment by CedrikNikita** [comment]
Thought we may introduce not only avoiding duplicate names, but also loading an additional names that were claimed between user interactions of this page. But i guess that is to tricky, because there are different cases where user may not undestand that loadMore button actually loaded something, I agree

File: store/oracles.js [hunk 1]
```diff
@@ -1,25 +1,31 @@
...
+      commit('setOracles', oracles)
     } catch (e) {
       console.log(e)
       commit('catchError', 'Error', { root: true })
     }
+  },
+  getMoreOracles: async function ({ state: { nextPageUrl }, commit }) {
+    if (!nextPageUrl) return
+    const oracles = await loadNextPage(nextPageUrl)
+    commit('setOracles', oracles)
```
Comment (davidyuk) [inline store/oracles.js:29]: Future step would be to extract a module that will manage `nextPageUrl`, `getLatest<>`, `getMore<>` for each entity. This would allow getting rid of a lot of duplicate code.

File: store/oracles.js [hunk 2]
```diff
@@ -1,25 +1,31 @@
...
-      commit('setOracles', oracles.data)
+      if (state.nextPageUrl) return
+      const oracles = await middleware.getActiveOracles()
+      commit('setOracles', oracles)
     } catch (e) {
       console.log(e)
       commit('catchError', 'Error', { root: true })
     }
+  },
+  getMoreOracles: async function ({ state: { nextPageUrl }, commit }) {
```
Comment (davidyuk) [inline store/oracles.js:26]:
```suggestion
  getMore: async function ({ state: { nextPageUrl }, commit }) {
```
I think the entity name is not necessary because all of this stuff in the context of a named vuex module

File: store/oracles.js [hunk 3]
```diff
@@ -1,25 +1,31 @@
...
+import { loadNextPage } from './utils'
 
 export const state = () => ({
-  oracles: {}
+  oracles: [],
+  nextPageUrl: ''
 })
 
 export const mutations = {
   setOracles (state, oracles) {
```
Comment (davidyuk) [inline store/oracles.js:9]: I would name it
```suggestion
  addOracles (state, oracles) {
```

File: store/utils.js [hunk 4]
```diff
@@ -74,6 +79,10 @@ export const initMiddleware = () => {
   return camelcaseKeysDeep(swg.api)
 }
 
+export const loadNextPage = async (nextPageUrl) => {
+  return camelcaseKeysDeep(await fetchJson(`${process.env.middlewareURL}/${nextPageUrl}`))
```
Comment (davidyuk) [inline store/utils.js:83]:
```suggestion
export const fetchMiddleware = async (path) => {
  return camelcaseKeysDeep(await fetchJson(`${process.env.middlewareURL}/${path}`))
```
it doesn't know anything about the next page 🤷‍♀️

File: store/names.js [hunk 5]
```diff
@@ -1,23 +1,33 @@
...
     } catch (e) {
       console.log(e)
       commit('catchError', 'Error', { root: true })
     }
   },
+  getMoreNames: async function ({ state: { nextPageUrl }, commit }) {
+    if (!nextPageUrl) return
+    const names = await loadNextPage(nextPageUrl)
+    commit('setNames', names)
+  },
```
Comment (davidyuk) [inline store/names.js:30]: Would be interesting to use [generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator) here, but I think they can't be passed over network :(

**Review by davidyuk — APPROVED** [review]
