### PR TITLE
fix(accountPage): display if the account is not found

### LINKED ISSUE #125: error if an account is "not found" according to node but received an AEX-9 token
image

I identified this issue when playing around with the token transfer page.

example:
- http://localhost:3000/tokens/ct_YxSqHHSEoRjpcdVzGC3Z6eFwxkiGrgezBcudRG9MauaVPfUd7 (token contract)
- http://localhost:3000/transactions/th_2FEbSajaz2Gb8WftaEq8Qi4MZtoZboq3X2YvxucVj4uRMjgzAa (transaction)
- http://localhost:3000/account/ak_2hh3hCqCR7n5c2fFzEZ4QPRiZgSV5cd4NNgrpBQEzGwwoaqcxx (recipient)

not sure what's the problem exactly. I thought the frontend handled this correctly. maybe it is related to the new feature.

### PR DESCRIPTION
**Pull request by AtanasKrondev**
Fixes #125 

If the account is non-existent it'll show like this:

Even if there's no such account there is info for the token transaction that still can be seen.

### CODE REVIEW

**Review by marc0olo — CHANGES_REQUESTED** [review]
haven't had a close look yet but I wouldn't display the "real error" message in that case.

I would favor sth. like:

**ACCOUNT TYPE** (as is)
unknown (in red with a small info icon tooltip next to it that says "The account has never been seen in the network."

File: partials/accountDetails.vue [hunk 1]
```diff
@@ -7,7 +7,22 @@
         title="Address"
         icon
       />
-      <AppDefinition title="Account type">
+      <AppDefinition
+        v-if="account.error"
+        title="Account type"
+      >
+        <div class="error">
+          UNKNOWN
```
Comment (marc0olo) [inline partials/accountDetails.vue:15]:
```suggestion
          unknown
```

**Review by marc0olo — CHANGES_REQUESTED** [review]
image

if possible the words should be in the next line instead of cut. in this case "see" + "n" doesn't look good.

also see suggestion => I would write "unknown" small as it is for the other types, too.

**Review by marc0olo — APPROVED** [review]
